name: Flag Request
description: Request a new flag to be added
title: "[Flag Request]: "
labels: ["enhancement", "flag request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new flag to be added to the site. This website is trying to document flags that are in use by the community, as well as some of the history that has led to the flags we have today.

        If you're a developer who has the know-how, check out our [contributing guide](https://github.com/s-thom/ourflags.lgbt/blob/main/docs/CONTRIBUTING.md) and see if you want to make the change yourself.
  - type: checkboxes
    id: in-use
    attributes:
      label: Is this flag suitable for the website?
      description: This question is a quick filter to remove meme flags and the like. Don't worry if your flag doesn't meet some of these, it may still be considered
      options:
        - label: This flag is part of pride history
        - label: This flag is in-use today
        - label: This flag is widely recognised by the rainbow community
  - type: textarea
    id: flag
    attributes:
      label: Describe the flag, its role in the community, and why it should be included
      description: You can attach an image by pasting it in. Sources are always appreciated
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/s-thom/ourflags.lgbt/blob/main/docs/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
