const DEFAULT_FAVICON_FLAG = "test1";

export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link
        href={`/images/favicons/${DEFAULT_FAVICON_FLAG}_32.png`}
        rel="shortcut icon"
        sizes="32x32"
        type="image/png"
      />
      <link
        href={`/images/favicons/${DEFAULT_FAVICON_FLAG}_128.png`}
        rel="shortcut icon"
        sizes="128x128"
        type="image/png"
      />
      <link
        href={`/images/favicons/${DEFAULT_FAVICON_FLAG}_192.png`}
        rel="shortcut icon"
        sizes="192x192"
        type="image/png"
      />
    </>
  );
}
