# Copyright (c) 2022 Stuart Thomson.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

name: Node.js CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Lint & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Generate data from content
        run: npm run generate-data
      - name: Run linters
        run: npm run lint
      - name: Build
        run: npm run build
  license-check:
    name: License Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run license check
        run: npm run license-check
